trigger:
  branches:
    include:
      - feature/*
      - main

pool: hamare_agentka_Jhund

stages:
- stage: TerraformPlan
  jobs:
  - job: Plan
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'D:\Dilip\kaluwa'
        backendServiceArm: 'AgentVinod2'
        backendAzureRmStorageAccountName: 'dilipstg1'
        backendAzureRmContainerName: 'dilip-con1'
        backendAzureRmKey: 'dku.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: 'D:\Dilip\kaluwa'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: 'D:\Dilip\kaluwa'
        environmentServiceNameAzureRM: 'AgentVinod2'

