trigger: none

pool: hamare_agentka_Jhund

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'D:\Dilip\kaluwa'
    backendServiceArm: 'serviceconnection1'
    backendAzureRmResourceGroupName: 'dilip-rg'
    backendAzureRmStorageAccountName: 'dilipstg2'
    backendAzureRmContainerName: 'dilip-con1'
    backendAzureRmKey: 'dku.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: 'D:\Dilip\kaluwa'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'D:\Dilip\kaluwa'
    environmentServiceNameAzureRM: 'serviceconnection1'

